import { Product } from "./definitions";

export const topProducts = [
  {
    id: 1,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    reviews: 530,
    discount_percentage: 20,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 2,
    title: "Brown Cardigan 2",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 3,
    title: "Brown Cardigan 3",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 4,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 5,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 6,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
];

export const featuredProducts = [
  {
    id: 1,
    title: "Western Jacket",
    desc: "A western jacket",
    image: {
      alt: "western jacket",
      src: "/placeholder/prod1.jpg",
      w: 1508,
      h: 2203,
    },
    discount_percentage: 40,
    items_left: 40,
    price: 50000,
    reviews: 400,
    rating: 4,
  },
  {
    id: 2,
    title: "Complete Wear",
    desc: "A complete outfit",
    image: { src: "/placeholder/prod2.jpg", w: 1666, h: 2487 },
    discount_percentage: 40,
    items_left: 30,
    price: 70000,
    reviews: 400,
    rating: 4,
  },
  {
    id: 3,
    title: "Gobbama Polo",
    desc: "Gobbama Polo",
    image: { src: "/placeholder/prod3.jpg", w: 2000, h: 2500 },
    discount_percentage: 40,
    items_left: 20,
    price: 55000,
    reviews: 400,
    rating: 4,
  },
  {
    id: 4,
    title: "German Suit",
    desc: "Suit",
    image: { src: "/placeholder/prod4.jpg", w: 1666, h: 2480 },
    discount_percentage: 40,
    items_left: 30,
    price: 75000,
    reviews: 430,
    rating: 4,
  },
  {
    id: 5,
    title: "Goldboy Top",
    desc: "shirt",
    image: { src: "/placeholder/prod5.jpg", w: 2000, h: 2500 },
    discount_percentage: 40,
    items_left: 30,
    price: 75000,
    reviews: 430,
    rating: 4,
  },
  {
    id: 5,
    title: "Blue Hoodie",
    desc: "hoodie",
    image: { src: "/placeholder/prod6.jpg", w: 1389, h: 1807 },
    discount_percentage: 40,
    items_left: 30,
    price: 75000,
    reviews: 430,
    rating: 4,
  },
];

export const featuredWeddingWears = {
  title: "Wear to wedding",
  desc: "We give couples a perfect touch for their wedding shoots!",
  images: [
    {
      id: 1,
      src: "/placeholder/wedding1.png",
      alt: "Couple in white t-shirts and jeans",
      w: 1065,
      h: 538,
    },
    {
      id: 2,
      src: "/placeholder/wedding2.jpg",
      alt: "Couple in gray hoodies  and sweatpants",
      w: 3733,
      h: 5600,
    },
    {
      id: 3,
      src: "/placeholder/wedding3.jpg",
      alt: "A couple",
      attr: {
        desc: "Photo by Oktay Köseoğlu",
        link: "https://www.pexels.com/photo/couple-in-retro-clothes-posing-on-balcony-14235300/",
      },
      w: 3936,
      h: 2389,
    },
    {
      id: 4,
      src: "/placeholder/wedding4.jpg",
      alt: "A couple in retro clothes posing on balcony",
      attr: {
        desc: "Photo by Oktay Köseoğlu",
        link: "https://www.pexels.com/photo/couple-in-retro-clothes-posing-on-balcony-14235300/",
      },
      w: 5905,
      h: 3937,
    },
    {
      id: 5,
      src: "/placeholder/wedding5.jpg",
      alt: "A couple outdoors",
      w: 5592,
      h: 3728,
    },
  ],
};

export const trendingProducts = [
  {
    id: 1,
    title: "Black Top",
    image: {
      src: "/placeholder/trending1.png",
      w: 612,
      h: 408,
    },
  },
  {
    id: 2,
    title: "Round Top",
    image: {
      src: "/placeholder/trending2.png",
      w: 408,
      h: 612,
    },
  },
  {
    id: 3,
    title: "White Top",
    image: {
      src: "/placeholder/trending3.png",
      w: 408,
      h: 612,
    },
  },
  {
    id: 4,
    title: "Black Shirt",
    image: {
      src: "/placeholder/trending4.png",
      w: 447,
      h: 557,
    },
  },
  {
    id: 5,
    title: "White Hoodie",
    image: {
      src: "/placeholder/trending5.png",
      w: 408,
      h: 612,
    },
  },
  {
    id: 6,
    title: "Red Hoodie",
    image: {
      src: "/placeholder/trending6.png",
      w: 612,
      h: 408,
    },
  },
  {
    id: 7,
    title: "Black Top",
    image: {
      src: "/placeholder/trending7.png",
      w: 408,
      h: 612,
    },
  },
  {
    id: 8,
    title: "Blue Jean",
    image: {
      src: "/placeholder/trending8.png",
      w: 431,
      h: 579,
    },
  },
  {
    id: 9,
    title: "Collar Hoodie",
    image: {
      src: "/placeholder/trending9.png",
      w: 408,
      h: 612,
    },
  },
  {
    id: 10,
    title: "Black Hat",
    image: {
      src: "/placeholder/trending10.png",
      w: 622,
      h: 401,
    },
  },
];

export const flashSaleProducts = [
  {
    id: 1,
    title: "Crispy Gown",
    items_left: 50,
    price: 100000,
    discount_percentage: 50,
    image: {
      src: "/placeholder/flash1.jpg",
      w: 1479,
      h: 2480,
    },
  },
  {
    id: 2,
    title: "Kiddies Top",
    items_left: 45,
    price: 150000,
    discount_percentage: 75,
    image: {
      src: "/placeholder/flash2.jpg",
      w: 1658,
      h: 2487,
    },
  },
  {
    id: 3,
    title: "Men German Suit",
    items_left: 45,
    price: 150000,
    discount_percentage: 15,
    image: {
      src: "/placeholder/flash3.jpg",
      w: 1855,
      h: 2500,
    },
  },
];
