import { Product } from "./definitions";

export const topProducts = [
  {
    id: 1,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    reviews: 530,
    discount_percentage: 20,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 2,
    title: "Brown Cardigan 2",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 3,
    title: "Brown Cardigan 3",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 4,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 5,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 6,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    discount_percentage: 20,
    reviews: 200,
    items_left: 30,
    price: 700000,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
];

export const featuredProducts: Product[] = [
  {
    id: 1,
    title: "Western Jacket",
    desc: "A western jacket",
    image: {
      alt: "western jacket",
      src: "/placeholder/prod1.jpg",
      w: 1508,
      h: 2203,
    },
    discount_percentage: 40,
    items_left: 40,
    price: 50000,
    reviews: 400,
    rating: 4,
  },
  {
    id: 2,
    title: "Complete Wear",
    desc: "A complete outfit",
    image: { src: "/placeholder/prod2.jpg", w: 1666, h: 2487 },
    discount_percentage: 40,
    items_left: 30,
    price: 70000,
    reviews: 400,
    rating: 4,
  },
  {
    id: 3,
    title: "Gobbama Polo",
    desc: "Gobbama Polo",
    image: { src: "/placeholder/prod3.jpg", w: 2000, h: 2500 },
    discount_percentage: 40,
    items_left: 20,
    price: 55000,
    reviews: 400,
    rating: 4,
  },
  {
    id: 4,
    title: "German Suit",
    desc: "Suit",
    image: { src: "/placeholder/prod4.jpg", w: 1666, h: 2480 },
    discount_percentage: 40,
    items_left: 30,
    price: 75000,
    reviews: 430,
    rating: 4,
  },
  {
    id: 5,
    title: "Goldboy Top",
    desc: "shirt",
    image: { src: "/placeholder/prod5.jpg", w: 2000, h: 2500 },
    discount_percentage: 40,
    items_left: 30,
    price: 75000,
    reviews: 430,
    rating: 4,
  },
  {
    id: 5,
    title: "Blue Hoodie",
    desc: "hoodie",
    image: { src: "/placeholder/prod6.jpg", w: 1389, h: 1807 },
    discount_percentage: 40,
    items_left: 30,
    price: 75000,
    reviews: 430,
    rating: 4,
  },
];
