export const topProducts = [
  {
    id: 1,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    reviews: 530,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 2,
    title: "Brown Cardigan 2",
    subtitle: "Nigerian Made",
    rating: 4.5,
    reviews: 530,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 3,
    title: "Brown Cardigan 3",
    subtitle: "Nigerian Made",
    rating: 4.5,
    reviews: 530,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 4,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    reviews: 530,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 5,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    reviews: 530,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
  {
    id: 6,
    title: "Brown Cardigan",
    subtitle: "Nigerian Made",
    rating: 4.5,
    reviews: 530,
    desc: "Do more for yourself by  shopping with a world class fashion design company.",
    image: {
      src: "/placeholder/image1.jpg",
      alt: "Man wearing cardigan",
      w: 2560,
      h: 2560,
    },
    features: [
      "User friendly",
      "Durable",
      "Long lasting",
      "Afordable",
      "Unique",
    ],
  },
];
